### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by iPaulPro** [bitclout/desktop#3]
What license is this code published under?

**Comment by dw5** [comment]
Desktop app is just a basic electron code, possibly boilerplate code hooked up to particular site

Technically unlicensed, or... Bitconeeeeeeeeeeeeeeeect license!

**Comment by dw5** [comment]
#2

**Comment by sull** [comment]
It is setup as a site-specific browser that offers a more controlled and secure sandboxed environment.

**Comment by castarco** [comment]
Even if it's a "sandboxed environment" it should have a proper license.

And going back to the "sandboxing" aspect, if one reads this: https://www.electronjs.org/docs/api/sandbox-option , it should be clear by now that the electron app is less secure than relying on the browser.

**Comment by maebeam** [comment]
Added MIT license and `sandbox: true`. Thank you both!
