### ISSUE TITLE
Electron Build Github Actions [Suggestion]

### ISSUE THREAD

**Issue by AroraShreshth** [bitclout/desktop#4]
## Github Action for Building Electron Application 
_Action to create Electron builds for Windows, Linux and Mac on the fly with each version update and automatically put into releases tab._

if fine with maintainers @maebeam will create a PR.

Profile : bitclout.com/u/shreshth

**Comment by maebeam** [comment]
I don't see a ton of value in building the app on github actions at the moment. We can't do automatic releases because the mac app needs to be signed and approved by apple. Gonna close for now, but thank you for the suggestion.

**Comment by DegenDudes** [comment]
https://localazy.com/blog/how-to-automatically-sign-macos-apps-using-github-actions
