### ISSUE TITLE
There is literally no code, no Dockerfile, nothing for anyone to see here.  Running this seems extremely risky.  I only see one README file.  Please share source code.

### ISSUE THREAD

**Issue by Barnacules** [bitclout/desktop#5]
There is literally no code, no Dockerfile, nothing for anyone to see here.  Running this seems extremely risky.  I only see one README file.  Please share source code.

__Originally posted by @maltokyo in https://github.com/cloutreactor/release/issues/8__

**Comment by iPaulPro** [comment]
https://github.com/bitclout/frontend
https://github.com/bitclout/core
https://github.com/bitclout/backend
https://github.com/bitclout/identity

**Comment by maltokyo** [comment]
That's the bitclout code, not the code for cloutreactor..

**Comment by diamondhands0** [comment]
Hey there, I'm not sure what this is referring to. As @iPaulPro said, all of the BitClout code and data is completely public. There are already many apps and project building on top of BitClout's open ecosystem that you can learn more about [here](https://bithunt.com).

This repo, aka the "desktop" repo, contains an Electron app that allows users to access the BitClout blockchain more securely. And the code for it is also completely public.

If you are referring to cloutreactor, that is a separate project run by Korbin. BitClout provides a totally open-source CPU miner that you can find [here](https://github.com/bitclout/backend/blob/main/scripts/run_remote_miner.sh). Korbin developed a GPU miner on his own after we fully open-sourced all of the BitClout code, and he is monetizing that as his own separate business. If you have issues related to that, I would send them his way and I'm sure he'd be happy to address them: https://github.com/cloutreactor

Closing this now as it is not relevant to this repository.
